baseURL = "https://iporsut.github.io/"
languageCode = "en-us"
title = "Weerasak Chongnguluam"
theme = "ananke"
disqusShortname = "iporsut"

[params]
  description = "Weerasak Chongnguluam's blog"
  facebook = "https://facebook.com/iporsut"
  twitter = "https://twitter.com/iporsut"
  github = "https://github.com/iporsut"
  background_color_class = "bg-black"
