baseURL = "https://iporsut.github.io/"
languageCode = "en-us"
title = "Weerasak Chongnguluam"
theme = "hugo-coder"
disqusShortname = "iporsut"

paginate = 20
canonifyurls = true

pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  author = "Weerasak Chongnguluam"
  info = "Software Engineer"
  description = "Weerasak Chongnguluam's blog"
  keywords = "blog,developer,programmer,personal"
  inverted = false

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/iporsut/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/iporsut/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
