baseURL = "https://iporsut.github.io/"
languageCode = "en-us"
title = "Weerasak Chongnguluam"
theme = "ananke"

[params]
  description = "Weerasak Chongnguluam's blog"
  facebook = "https://facebook.com/iporsut"
  twitter = "https://twitter.com/iporsut"
  github = "https://github.com/iporsut"
